### ISSUE TITLE
`Extra attributes from the server: data-fr-js-modal-button`

### ISSUE THREAD

**Issue by arnaudambro** [codegouvfr/react-dsfr#305]
Hello

I've this warning using react-dsfr in my Remix project (here: https://github.com/betagouv/zacharie/tree/24f0594140d20aa8d93f271947c8dd62fdb83112)

I have no clue how to try and fix it...

```warning
Warning: Extra attributes from the server: data-fr-js-modal-button
    at button
    at http://localhost:3232/node_modules/.vite/deps/chunk-EIDWZ6ND.js?v=628cc138:41:15
    at fr-theme-modal-modal
    at Display (http://localhost:3232/node_modules/.vite/deps/@codegouvfr_react-dsfr_Header.js?v=628cc138:426:17)
    at http://localhost:3232/node_modules/.vite/deps/@codegouvfr_react-dsfr_Header.js?v=628cc138:752:11
    at TableauDeBordLayout (http://localhost:3232/app/routes/tableau-de-bord.tsx:9:18)
    at RenderedRoute (http://localhost:3232/node_modules/.vite/deps/chunk-7GTNRECA.js?v=628cc138:401:5)
    at Outlet (http://localhost:3232/node_modules/.vite/deps/chunk-7GTNRECA.js?v=628cc138:739:26)
    at HoneypotProvider (http://localhost:3232/node_modules/.vite/deps/remix-utils_honeypot_react.js?v=628cc138:27:29)
    at App (http://localhost:3232/app/root.tsx:199:7)
    at body
    at html
    at Layout (http://localhost:3232/app/root.tsx:31:3)
    at RenderedRoute (http://localhost:3232/node_modules/.vite/deps/chunk-7GTNRECA.js?v=628cc138:401:5)
    at RenderErrorBoundary (http://localhost:3232/node_modules/.vite/deps/chunk-7GTNRECA.js?v=628cc138:361:5)
    at DataRoutes (http://localhost:3232/node_modules/.vite/deps/chunk-7GTNRECA.js?v=628cc138:1394:5)
    at Router (http://localhost:3232/node_modules/.vite/deps/chunk-7GTNRECA.js?v=628cc138:746:15)
    at RouterProvider (http://localhost:3232/node_modules/.vite/deps/chunk-7GTNRECA.js?v=628cc138:1209:5)
    at RemixErrorBoundary (http://localhost:3232/node_modules/.vite/deps/chunk-7GTNRECA.js?v=628cc138:2757:5)
    at RemixBrowser (http://localhost:3232/node_modules/.vite/deps/chunk-7GTNRECA.js?v=628cc138:4294:46)
```

**Comment by garronej** [comment]
Hello @arnaudambro,  

Assuming you're using the components exposed by react-dsfr, this error is very strange.  

This attribute is added dynamically by the JavaScript code of `@gouvfr/dsfr`. This code isn't loaded on the backend during SSR. It cannot possibly be. If it was many errors would be thrown.  

If you can produce a reproduction repo with precise steps to reproduce I'll be able to debug.

**Comment by arnaudambro** [comment]
> If you can produce a reproduction repo with precise steps to reproduce I'll be able to debug.

this is the repo I'm working on, with the code as is https://github.com/betagouv/zacharie/tree/24f0594140d20aa8d93f271947c8dd62fdb83112

the file your might be interested in is `./app/entry.client.tsx` I think

**Comment by garronej** [comment]
Please provide the exact command to reproduce and where I should navigate to reproduce the error.

**Comment by arnaudambro** [comment]
```
git clone git@github.com:betagouv/zacharie.git
cd ./zacharie
git checkout 59b8832994911b2ce3523f8bee114048a6ddb8d2
yarn install
yarn dev-test-react-dsfr
```

this should work

**Comment by garronej** [comment]
I'm not getting the error described:  

<img width="2056" alt="image" src="https://github.com/user-attachments/assets/9050b14c-580b-41fa-898a-eb4f95927785">

**Comment by arnaudambro** [comment]
mmm yes, my bad, it's once you're logged in

then on the url `http://localhost:3232/tableau-de-bord`

if you remove everything except the header in `./app/tableau-de-bord.tsx` you still get the error

```tsx
import { Header } from "@codegouvfr/react-dsfr/Header";

export default function TableauDeBordLayout() {
  return (
    <>
      <Header
        brandTop={
          <>
            Ministère
            <br />
            de l'Agriculture
          </>
        }
        homeLinkProps={{
          href: "/",
          title: "Zacharie - Ministère de l'Agriculture",
        }}
        id="fr-header-header-with-quick-access-items"
        serviceTagline="La Fiche d’Examen Initial (FEI) simplifiée"
        serviceTitle="Zacharie"
      />
    </>
  );
}
```

I made a branch for this test: https://github.com/betagouv/zacharie/tree/test--warning-dsfr

**Comment by garronej** [comment]
I still don't see the error you're refering to in this issue:  

<img width="753" alt="image" src="https://github.com/user-attachments/assets/012fd40c-c43f-45e0-b066-1e58098236a1">

<img width="2056" alt="image" src="https://github.com/user-attachments/assets/d4c9ff59-1704-4e5f-b59d-2cc5f8d17960">

**Comment by carolineBda** [comment]
Hello, we're seeing similar warning in our project (only in dev mode) :

![Screenshot from 2024-09-12 15-11-28](https://github.com/user-attachments/assets/549c8f08-b320-4258-b9ad-cfa7dc5a0371)

It can be reproduced on this PR :
https://github.com/SocialGouv/code-du-travail-numerique/pull/6078

Run
```
yarn && yarn build
yarn dev:frontend
```
Then go to 
`http://localhost:3000/mentions-legales`

**Comment by garronej** [comment]
Hello @carolineBda,  

This is not the same error and not the same meta framwork. Please open a new issue.

**Comment by carolineBda** [comment]
ok :+1:

**Comment by garronej** [comment]
@carolineBda and unfortunatly, I can't reproduce either:  

![image](https://github.com/user-attachments/assets/51eaa3e0-797f-48ec-9795-9d04d1d5ec48)

**Comment by arnaudambro** [comment]
> I still don't see the error you're refering to in this issue:
> 


are you sure you're on the branch ? https://github.com/betagouv/zacharie/tree/test--warning-dsfr
cause the error shows you need a postgres db but in that branch I removed the dependency to this - and it works fine on my computer

**Comment by garronej** [comment]
Yes. I was on the branch. I'll try again after your update

**Comment by garronej** [comment]
But generally please provide the exact commands to reproduce.

**Comment by garronej** [comment]
Still can reproduce, neither with chrome or firefox, neither with network throtling.  

The error I'm getting is:  

<img width="2056" alt="image" src="https://github.com/user-attachments/assets/648cdff5-21e7-4046-97d9-41dd670ac5ee">

I can look at this but this isn't the same error you're refering to, it's related to Remix Link component.  

Maybe produce a dump of the error with https://www.replay.io/ ?

**Comment by garronej** [comment]
Maybe try clearing your browser cache as well.  

<img width="1361" alt="image" src="https://github.com/user-attachments/assets/c27a4d71-a070-48d5-b804-62f7abe9132f">

It's maybe due to the fact that you've done this:  

<img width="280" alt="image" src="https://github.com/user-attachments/assets/ff483ea5-6149-4a27-b552-ed93d2518b54">

**Comment by arnaudambro** [comment]
still here...

sorry I have no time right now to dig in a little bit more, but in October/November I think I'll be able to

Thanks anyway, great job done there !

**Comment by lutangar** [comment]
This error appears when the `lang` attribute is set on the `<DsfrProvider />` component  and when using **Next.js**  App router :

Here is a minimum layout to reproduce the error :

`app/layout.tsx`
```tsx
import { type PropsWithChildren } from 'react';
import { DsfrProvider } from '@codegouvfr/react-dsfr/next-appdir/DsfrProvider';
import { getHtmlAttributes } from '@codegouvfr/react-dsfr/next-appdir/getHtmlAttributes';
import { StartDsfr } from '@/components/StartDsfr';

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="fr" {...getHtmlAttributes({ defaultColorScheme: 'light', lang: 'fr' })}>
      <head>
        <StartDsfr />
      </head>
      <body>
        <DsfrProvider lang="fr">{children}</DsfrProvider>
      </body>
    </html>
  );
};

export default RootLayout;
```

> For the `<StartDsfr />` component see : 
> https://react-dsfr.codegouv.studio/routing

**Comment by garronej** [comment]
Hello @lutangar, I dobt that is the root cause of the issue.  

Here again I can't reproduce, I tried with the [Next App Router Starter](https://github.com/garronej/react-dsfr-next-appdir-demo).  

I'm down to fix whatever as long as you can provide me a reproduction path.

**Comment by moroine** [comment]
@garronej 

I have such similar issue, but on my side it's an hydratation error between Server & Client.

Here is a reproduction of the problem https://github.com/mission-apprentissage/react-dsfr-next-appdir-demo/commit/971280055dd7c2f636aa14be305699075ec62b9d 

That's a different error message, but I think it's all related to Suspense boundary

**Comment by garronej** [comment]
Hello,

Support for **Next.js 15** just landed!

Updated documentation:  
https://react-dsfr.codegouv.studio/#next-js-app-router

Updated starter project:  
https://github.com/garronej/react-dsfr-next-appdir-demo

Unfortunately, I couldn’t make it work without introducing **breaking changes**.  
Please refer to the following commit to see what you’ll need to update:  
https://github.com/garronej/react-dsfr-next-appdir-demo/commit/aaabb7925823fb163b83ffd438da7264084b629b

---Rant time

Next.js is... a pain.

It keeps shipping broken features, and the only reason it's even usable is because the rest of the ecosystem constantly works around its limitations. Development is **incredibly slow**, and while Turbopack helps a bit, it also breaks a lot of packages.

Self-hosting is unnecessarily difficult. The mental model is convoluted, and the folder structure is rigid and unintuitive. (Just look at how messy the setup for `react-dsfr` is — and sadly, there's no cleaner way to do it.)

I even had to make you install **SASS** because their built-in CSS compiler is broken.  
To make things worse, they recently changed the order in which components render — forcing me to introduce breaking changes yet again.

Sorry for the rant — just needed to let it out. I’ve spent *countless hours* making my libraries work with Next.js, and every time something breaks, users assume it’s the lib’s fault.

Honestly, I believe **TanStack Start** (or even **React Router** / ex-Remix) are better full-stack frameworks. I really hope they gain more traction.

Thanks for sticking with it!

**Comment by moroine** [comment]
I had a build issue which is fixed with the latest relase, thanks!

But I'm still experiencing hydratation errors (https://github.com/mission-apprentissage/react-dsfr-next-appdir-demo) 


@garronej what about creating Github release to add notes including potential breaking change ?

**Comment by garronej** [comment]
Yes sorry @moroine the hydratation error is still present.  I'm looking into it.

**Comment by garronej** [comment]
> @garronej what about creating GitHub releases to add notes, including potential breaking changes?

In my experience, very few people actually read release notes and we release too often.  
Also, maintaining this project is already quite time consuming, and we've received zero support—past or present—from the SIG or DINUM.

That said, here’s what I *can* commit to:

- Ensuring compatibility with the latest version of Next.js.
- Keeping the documentation fully up to date.
- Keeping the starter project updated: https://github.com/garronej/react-dsfr-next-appdir-demo
- Avoiding silent breaking changes: if something breaks, it will trigger type errors.

Beyond that, I simply don't have the bandwidth to provide scheduled updates or detailed migration guides.
